### ISSUE TITLE
deployment fails - eslint problem - requires hotfix!

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/code-component#39]
While deploying the component to xpc, got the following error:

```
> eio-code-component@1.2.0 lint /tmp/build
       > eslint .


       /tmp/build/spec/code.spec.js
       95:1  error  More than 1 blank line not allowed  no-multiple-empty-lines
```

full deployment log below:

```
Enumerating objects: 404, done.
Counting objects: 100% (404/404), done.
Delta compression using up to 4 threads
Compressing objects: 100% (152/152), done.
Writing objects: 100% (404/404), 200.73 KiB | 33.45 MiB/s, done.
Total 404 (delta 210), reused 404 (delta 210)
remote: Resolving deltas: 100% (210/210), done.
remote: Received push to: xpc@git.elastic.io/code.git
remote: Team: xpc
remote: Repository: code
remote: Revision: 2320a1d0728f800019590bbbfba1db6b740bd345
remote: Build ID: f17a546e-a00d-423f-85d2-b7d7604afabd
remote: Successfully validated parameters
remote: Authorizing access of xpc to code
remote: (node:4485) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
remote: About to build slug
remote: mkdir
remote: cat | tar -xm
-----> Elastic.io Node.js component app detected
-----> Compiling buildpack...
       Build root dir: /tmp/build
       Cache root dir: /tmp/cache

-----> Reading application state
       package.json...
       build directory...
       cache directory...
       environment variables...

       Node engine:         >=12.13.0
       Npm engine:          unspecified
       Start mechanism:     none
       node_modules source: package.json
       node_modules cached: false

       NPM_CONFIG_PRODUCTION=false
       NODE_MODULES_CACHE=true

-----> Installing binaries
       Resolving node version >=12.13.0 via semver.io...
       Downloading and installing node 14.4.0...
       Using default npm version: 6.14.5

-----> Building dependencies
       Disabling Certificate Authority by NPM
       Installing node modules

       > dtrace-provider@0.8.7 install /tmp/build/node_modules/dtrace-provider
       > node-gyp rebuild || node suppress-error.js

       make: Entering directory `/tmp/build/node_modules/dtrace-provider/build'
       TOUCH Release/obj.target/DTraceProviderStub.stamp
       make: Leaving directory `/tmp/build/node_modules/dtrace-provider/build'
       npm WARN eslint-config-airbnb@18.0.1 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
       npm WARN eslint-config-airbnb@18.0.1 requires a peer of eslint-plugin-react@^7.14.3 but none is installed. You must install peer dependencies yourself.
       npm WARN eslint-config-airbnb@18.0.1 requires a peer of eslint-plugin-react-hooks@^1.7.0 but none is installed. You must install peer dependencies yourself.
       npm WARN eslint-config-airbnb-base@14.2.0 requires a peer of eslint@^5.16.0 || ^6.8.0 || ^7.2.0 but none is installed. You must install peer dependencies yourself.
       npm WARN eslint-config-airbnb-base@14.2.0 requires a peer of eslint-plugin-import@^2.21.2 but none is installed. You must install peer dependencies yourself.

       added 369 packages from 1068 contributors and audited 369 packages in 13.861s

       19 packages are looking for funding
       run `npm fund` for details

       found 14 vulnerabilities (10 low, 4 high)
       run `npm audit fix` to fix them, or `npm audit` for details

-----> Validating Sailor compatibility
       Validating Sailor version 2.6.7 compatibility with Node.js version >=12.13.0
       npm WARN @elastic.io/sailor-compatibility@1.0.0 No description
       npm WARN @elastic.io/sailor-compatibility@1.0.0 No repository field.

       added 3 packages from 2 contributors and audited 3 packages in 0.379s
       found 0 vulnerabilities

       Installed required dependencies

-----> Running tests

       > eio-code-component@1.2.0 pretest /tmp/build
       > npm run lint


       > eio-code-component@1.2.0 lint /tmp/build
       > eslint .


       /tmp/build/spec/code.spec.js
       95:1  error  More than 1 blank line not allowed  no-multiple-empty-lines

       ✖ 1 problem (1 error, 0 warnings)
       1 error and 0 warnings potentially fixable with the `--fix` option.

remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! eio-code-component@1.2.0 lint: `eslint .`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the eio-code-component@1.2.0 lint script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2020-06-12T16_41_19_220Z-debug.log
remote: npm ERR! Test failed.  See above for more details.

-----> Build failed

       WARNING: Avoid semver ranges starting with '>' in engines.node

       We're sorry this build is failing! If you can't find the issue in component code,
       please submit a ticket so we can help: https://support.elastic.io
       You can also try upgrading Sailor to the most recent version. Check out
       https://www.npmjs.com/package/elasticio-sailor-nodejs

       Your elastic.io team
remote:
remote:
remote: Removing build container and slug
remote: Saving build
remote: Detaching from log stream
remote: Build failed
remote: Error: Appbuilder failed with code 1
remote: Error: Appbuilder failed with code 1
remote:     at ChildProcess.<anonymous> (/home/node/gitreceiver/src/lib/builder.js:74:31)
remote:     at ChildProcess.emit (events.js:315:20)
remote:     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
remote: {"name":"gitreceiver","hostname":"gitreceiver-6485c4bb79-9hqwk","pid":"4485","level":"50","err":{"message":"Appbuilder failed with code 1","name":"Error","stack":"Error: Appbuilder failed with code 1\n    at ChildProcess.<anonymous> (/home/node/gitreceiver/src/lib/builder.js:74:31)\n    at ChildProcess.emit (events.js:315:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)"},"msg":"Appbuilder failed with code 1","time":"2020-06-12T16:41:46.236Z","v":"0"}
To xpc:code.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'xpc@xpc:code.git'
```

**Comment by denyshld** [comment]
Fixed. Buildable version is in `master` branch now: https://github.com/elasticio/code-component
